#!/bin/bash --login
echo "Starting Topological Host Inventory Sync API"
source config.sh
source init-common.sh

cd $TOPOLOGICAL_HOST_INVENTORY_SYNC_DIR

env METRICS_PORT=${METRICS_PORT} TOPOLOGICAL_INVENTORY_API_SERVICE_HOST=${TOPOLOGICAL_INVENTORY_API_HOST} HOST_INVENTORY_API=${HOST_INVENTORY_API} TOPOLOGICAL_INVENTORY_INGRESS_API_SERVICE_HOST=${INGRESS_API_HOST} TOPOLOGICAL_INVENTORY_INGRESS_API_SERVICE_PORT=${INGRESS_API_PORT} bin/host-inventory-sync
